export const RPC_CONFIGS = [
  {
    label: 'Warden Protocol Testnet',
    COMETBFT_RPC_API: 'https://rpc Ward3n.xyz',
    COSMOS_SDK_API: 'https://api.ward3n.xyz',
    EXPLORER_API: 'https://api.ward3n.xyz',
    EXPLORER_URL: 'https://explorer.wardenprotocol.org',
    NETWORK_NAME: 'wardenprotocol',
    CHAIN_ID: 'warden-testnet',
    COIN_DENOM: 'uward',
    COIN_DISPLAY: 'WARD',
    COIN_DECIMALS: 6,
  },
  {
    label: 'Osmosis Testnet',
    COMETBFT_RPC_API: 'https://testnet-rpc.osmosis.zone',
    COSMOS_SDK_API: 'https://testnet-rest.osmosis.zone',
    EXPLORER_API: 'https://testnet-rest.osmosis.zone',
    EXPLORER_URL: 'https://testnet.osmosis.explorers.guru',
    NETWORK_NAME: 'osmosis',
    CHAIN_ID: 'osmo-test-5',
    COIN_DENOM: 'uosmo',
    COIN_DISPLAY: 'OSMO',
    COIN_DECIMALS: 6,
  },
  {
    label: 'Cosmos Hub Testnet',
    COMETBFT_RPC_API: 'https://rpc.sentry-02.theta-testnet.polypore.xyz',
    COSMOS_SDK_API: 'https://api.sentry-02.theta-testnet.polypore.xyz',
    EXPLORER_API: 'https://api.sentry-02.theta-testnet.polypore.xyz',
    EXPLORER_URL: 'https://testnet.cosmos.network',
    NETWORK_NAME: 'cosmoshub',
    CHAIN_ID: 'theta-testnet-001',
    COIN_DENOM: 'uatom',
    COIN_DISPLAY: 'ATOM',
    COIN_DECIMALS: 6,
  },
  {
    label: 'Joltify Testnet',
    COMETBFT_RPC_API: 'https://joltify-testnet-rpc.theamsolutions.info',
    COSMOS_SDK_API: 'https://joltify-testnet-api.theamsolutions.info',
    EXPLORER_API: 'https://joltify-testnet-api.theamsolutions.info',
    EXPLORER_URL: 'https://explorer.joltify.io/joltify-testnet',
    NETWORK_NAME: 'joltify',
    CHAIN_ID: 'joltify_9000-1',
    COIN_DENOM: 'ujolt',
    COIN_DISPLAY: 'JOLT',
    COIN_DECIMALS: 18,
  }
];

export const ROUTES = {
  DASHBOARD: 'dashboard',
  VALIDATORS: 'validators',
  VALIDATOR_DETAIL: 'validator_detail',
  UPTIME: 'uptime',
  BLOCKS_LIST: 'blocks_list',
  TXS: 'txs',
  PROPOSALS: 'proposals',
  MEMPOOL: 'mempool',
  NET_INFO: 'net_info',
  HEALTH: 'health',
  SEARCH: 'search',
};
